spring.application.name=TestApp
spring.datasource.url=jdbc:postgresql://localhost:5432/test_app_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8082
spring.jpa.hibernate.ddl-auto=update
